# -*- coding: utf-8 -*-
"""ЛАБОРАТОРНАЯ3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pb0dTKwBJx_AaO9qOVm4CO6qyp1aTmf3
"""

#1111111111111111111111111
print('Введите число месяца')
x = int(input())
if(x == 1):
    print('Январь')
elif(x == 2):
    print('Февраль')
elif(x==3):
    print('Март')
elif(x==4):
    print('Апрель')
elif(x==5):
    print('Май')
elif(x==6):
    print('Июнь')
elif(x==7):
    print('Июль')
elif(x==8):
    print('Август')
elif(x==9):
    print('Сентябрь')
elif(x==10):
    print('Октябрь')
elif(x==11):
    print('Ноябрь')
elif(x==12):
    print('Декабрь')
else:
    print('Такого месяца нет')

##22222222222222222222222
x = int(input())
if(x%2==0):
    print('Четное')
else:
    print('Нечетное')

##333333333333333333333
N = int(input())
if(N>40):
    print('stonks')
else:
    print('not stonks')

#44444444444444444444444444
print('is_year_lip')
x = int(input())
if(x%4==0)and((x%100!=0)or(x%400==0)):
    print('True')
else:
    print("False")

#5555555555555555555555555
n = int(input())
c = 0
for i in range(2,n//2+1):
    if (n%i==0):
        c += 1
if c <= 0:
    print('Число простое')
else:
    print('Нет')

#6666666666666666666
a = float(input())
b = float(input())

if (a / b==3.6) or (b > abs(-138 / 2) ** 1.3) and (b < (abs((-69 / 28 ** 5.1) * 4))):
    c = a + b
    a = c - a
    b = c - b
print(a)
print(b)

#77777777777 
a =[0,0,0,0,0]
counter1 = 0  #ЧЕТНОСТЬ
counter2 = 0  #ОТРИЦАТЕЛЬНОСТЬ
counter3 = 0  #ПРОМЕЖУТОК(-256;1024)
for i in range(5):
  a[i] = int(input())
  if a[i]%2==0:
    counter1 +=1
  if a[i]<0:
    counter2 +=1
  if a[i]>-256 and a[i]<1024:
    counter3 +=1
if  a[0]== a[1]or a[0]== a[2]or a[0]== a[3]or a[0]== a[4]or a[1]==a[2]or a[1]==a[3]or a[1]== a[4]or a[2]== a[3]or a[2]== a[4]or a[3]== a[4]:
  print('Какие-то числа совпадают')
print('Четных:',counter1)
print('Отрицательных:', counter2)
print('Лежащих в промежутке(-256;1024):', counter3)

#ЗАДАЧА ПОВЫШЕННОЙ СЛОЖНОСТИ
a = int(input())
b = int(input())
c = int(input())
x = ((a**2 + b**3)*4)//(c+3)
if(x%2==0):
   print('Четное')
else:
   print('Нечетное')